### ISSUE TITLE
Change CDN URL in README from RawGit to jsDelivr

### ISSUE THREAD

**Issue by scriptom** [bullhorn/bullhorn-icons#50]
As of 2019, [RawGit has been sunset](https://rawgit.com/), however README.me still encourages new projects to use its CDN. Right now, there's a redirection in place from RawGit to jsDelivr, however in practice this has shown to be poorly effective, and thus should not be relied upon.

The ask here is to update the RawGit CDN reference in the README.md example to use jsDelivr.
So that
```
/* RawGit for GitHub Version*/
<link rel="stylesheet" type="text/css" href="//cdn.rawgit.com/bullhorn/bullhorn-icons/v2.2.0/fonts/Bullhorn-Glyphicons.css"/>
```
becomes
```
/* jsDelivr for GitHub Version*/
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/bullhorn/bullhorn-icons@v2.2.0/fonts/Bullhorn-Glyphicons.css"/>
```

**Comment by ndickerson** [comment]
Updated. Thanks for noticing that!
